// flow-typed signature: 11483e26e7a0a15f8941ed434f234959
// flow-typed version: <<STUB>>/leaflet-timedimension_vhttps://github.com/Jagatmachines/Leaflet.TimeDimension.git/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-timedimension'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet-timedimension' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet-timedimension/dist/leaflet.timedimension.min' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/dist/leaflet.timedimension.src' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/dist/leaflet.timedimension.src.withlog' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/baselayers' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example1' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example10' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example11' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example12' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example13' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example14' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example15' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example16' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example2' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example3' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example4' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example5' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example6' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example7' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example8' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/example9' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/extras/leaflet.timedimension.circlelabelmarker' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/extras/leaflet.timedimension.layer.wms.timeseries' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/extras/leaflet.timedimension.tilelayer.portus' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/examples/js/vendor/NonTiledLayer' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/Gruntfile' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/src/leaflet.timedimension.control' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/src/leaflet.timedimension' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/src/leaflet.timedimension.layer.geojson' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/src/leaflet.timedimension.layer' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/src/leaflet.timedimension.layer.wms' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/src/leaflet.timedimension.player' {
  declare module.exports: any;
}

declare module 'leaflet-timedimension/src/leaflet.timedimension.util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet-timedimension/dist/leaflet.timedimension.min.js' {
  declare module.exports: $Exports<'leaflet-timedimension/dist/leaflet.timedimension.min'>;
}
declare module 'leaflet-timedimension/dist/leaflet.timedimension.src.js' {
  declare module.exports: $Exports<'leaflet-timedimension/dist/leaflet.timedimension.src'>;
}
declare module 'leaflet-timedimension/dist/leaflet.timedimension.src.withlog.js' {
  declare module.exports: $Exports<'leaflet-timedimension/dist/leaflet.timedimension.src.withlog'>;
}
declare module 'leaflet-timedimension/examples/js/baselayers.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/baselayers'>;
}
declare module 'leaflet-timedimension/examples/js/example1.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example1'>;
}
declare module 'leaflet-timedimension/examples/js/example10.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example10'>;
}
declare module 'leaflet-timedimension/examples/js/example11.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example11'>;
}
declare module 'leaflet-timedimension/examples/js/example12.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example12'>;
}
declare module 'leaflet-timedimension/examples/js/example13.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example13'>;
}
declare module 'leaflet-timedimension/examples/js/example14.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example14'>;
}
declare module 'leaflet-timedimension/examples/js/example15.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example15'>;
}
declare module 'leaflet-timedimension/examples/js/example16.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example16'>;
}
declare module 'leaflet-timedimension/examples/js/example2.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example2'>;
}
declare module 'leaflet-timedimension/examples/js/example3.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example3'>;
}
declare module 'leaflet-timedimension/examples/js/example4.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example4'>;
}
declare module 'leaflet-timedimension/examples/js/example5.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example5'>;
}
declare module 'leaflet-timedimension/examples/js/example6.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example6'>;
}
declare module 'leaflet-timedimension/examples/js/example7.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example7'>;
}
declare module 'leaflet-timedimension/examples/js/example8.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example8'>;
}
declare module 'leaflet-timedimension/examples/js/example9.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/example9'>;
}
declare module 'leaflet-timedimension/examples/js/extras/leaflet.timedimension.circlelabelmarker.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/extras/leaflet.timedimension.circlelabelmarker'>;
}
declare module 'leaflet-timedimension/examples/js/extras/leaflet.timedimension.layer.wms.timeseries.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/extras/leaflet.timedimension.layer.wms.timeseries'>;
}
declare module 'leaflet-timedimension/examples/js/extras/leaflet.timedimension.tilelayer.portus.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/extras/leaflet.timedimension.tilelayer.portus'>;
}
declare module 'leaflet-timedimension/examples/js/vendor/NonTiledLayer.js' {
  declare module.exports: $Exports<'leaflet-timedimension/examples/js/vendor/NonTiledLayer'>;
}
declare module 'leaflet-timedimension/Gruntfile.js' {
  declare module.exports: $Exports<'leaflet-timedimension/Gruntfile'>;
}
declare module 'leaflet-timedimension/src/leaflet.timedimension.control.js' {
  declare module.exports: $Exports<'leaflet-timedimension/src/leaflet.timedimension.control'>;
}
declare module 'leaflet-timedimension/src/leaflet.timedimension.js' {
  declare module.exports: $Exports<'leaflet-timedimension/src/leaflet.timedimension'>;
}
declare module 'leaflet-timedimension/src/leaflet.timedimension.layer.geojson.js' {
  declare module.exports: $Exports<'leaflet-timedimension/src/leaflet.timedimension.layer.geojson'>;
}
declare module 'leaflet-timedimension/src/leaflet.timedimension.layer.js' {
  declare module.exports: $Exports<'leaflet-timedimension/src/leaflet.timedimension.layer'>;
}
declare module 'leaflet-timedimension/src/leaflet.timedimension.layer.wms.js' {
  declare module.exports: $Exports<'leaflet-timedimension/src/leaflet.timedimension.layer.wms'>;
}
declare module 'leaflet-timedimension/src/leaflet.timedimension.player.js' {
  declare module.exports: $Exports<'leaflet-timedimension/src/leaflet.timedimension.player'>;
}
declare module 'leaflet-timedimension/src/leaflet.timedimension.util.js' {
  declare module.exports: $Exports<'leaflet-timedimension/src/leaflet.timedimension.util'>;
}
