// flow-typed signature: a528c98ad48868daa7a7e345ca1cfece
// flow-typed version: <<STUB>>/leaflet-elevation-v3_vhttps://github.com/Jagatmachines/leaflet-elevation.git/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-elevation-v3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet-elevation-v3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet-elevation-v3/leaflet-elevation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet-elevation-v3/leaflet-elevation.js' {
  declare module.exports: $Exports<'leaflet-elevation-v3/leaflet-elevation'>;
}
