// flow-typed signature: 0eb11f8bde9cf1ad7ffcfac7f3cfb204
// flow-typed version: <<STUB>>/leaflet-ant-path_v^1.2.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-ant-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet-ant-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet-ant-path/dist/leaflet-ant-path.es6' {
  declare module.exports: any;
}

declare module 'leaflet-ant-path/dist/leaflet-ant-path' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet-ant-path/dist/leaflet-ant-path.es6.js' {
  declare module.exports: $Exports<'leaflet-ant-path/dist/leaflet-ant-path.es6'>;
}
declare module 'leaflet-ant-path/dist/leaflet-ant-path.js' {
  declare module.exports: $Exports<'leaflet-ant-path/dist/leaflet-ant-path'>;
}
