// flow-typed signature: 74902df1687aac44e6820252a24aaf8a
// flow-typed version: <<STUB>>/leaflet-polylinedecorator_v^1.6.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaflet-polylinedecorator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaflet-polylinedecorator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaflet-polylinedecorator/dist/leaflet.polylineDecorator' {
  declare module.exports: any;
}

declare module 'leaflet-polylinedecorator/example/example' {
  declare module.exports: any;
}

declare module 'leaflet-polylinedecorator/rollup.config' {
  declare module.exports: any;
}

declare module 'leaflet-polylinedecorator/src/L.PolylineDecorator' {
  declare module.exports: any;
}

declare module 'leaflet-polylinedecorator/src/L.Symbol' {
  declare module.exports: any;
}

declare module 'leaflet-polylinedecorator/src/patternUtils' {
  declare module.exports: any;
}

declare module 'leaflet-polylinedecorator/tests/projectPatternOnPointPath' {
  declare module.exports: any;
}

declare module 'leaflet-polylinedecorator/tests/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaflet-polylinedecorator/dist/leaflet.polylineDecorator.js' {
  declare module.exports: $Exports<'leaflet-polylinedecorator/dist/leaflet.polylineDecorator'>;
}
declare module 'leaflet-polylinedecorator/example/example.js' {
  declare module.exports: $Exports<'leaflet-polylinedecorator/example/example'>;
}
declare module 'leaflet-polylinedecorator/rollup.config.js' {
  declare module.exports: $Exports<'leaflet-polylinedecorator/rollup.config'>;
}
declare module 'leaflet-polylinedecorator/src/L.PolylineDecorator.js' {
  declare module.exports: $Exports<'leaflet-polylinedecorator/src/L.PolylineDecorator'>;
}
declare module 'leaflet-polylinedecorator/src/L.Symbol.js' {
  declare module.exports: $Exports<'leaflet-polylinedecorator/src/L.Symbol'>;
}
declare module 'leaflet-polylinedecorator/src/patternUtils.js' {
  declare module.exports: $Exports<'leaflet-polylinedecorator/src/patternUtils'>;
}
declare module 'leaflet-polylinedecorator/tests/projectPatternOnPointPath.js' {
  declare module.exports: $Exports<'leaflet-polylinedecorator/tests/projectPatternOnPointPath'>;
}
declare module 'leaflet-polylinedecorator/tests/utils.js' {
  declare module.exports: $Exports<'leaflet-polylinedecorator/tests/utils'>;
}
