// flow-typed signature: b5d7839ab7fb39bf8bda299d1facbf6c
// flow-typed version: <<STUB>>/noty_v^3.2.0-beta/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'noty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'noty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'noty/lib/noty' {
  declare module.exports: any;
}

declare module 'noty/lib/noty.min' {
  declare module.exports: any;
}

declare module 'noty/src/api' {
  declare module.exports: any;
}

declare module 'noty/src/button' {
  declare module.exports: any;
}

declare module 'noty/src/index' {
  declare module.exports: any;
}

declare module 'noty/src/push' {
  declare module.exports: any;
}

declare module 'noty/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'noty/lib/noty.js' {
  declare module.exports: $Exports<'noty/lib/noty'>;
}
declare module 'noty/lib/noty.min.js' {
  declare module.exports: $Exports<'noty/lib/noty.min'>;
}
declare module 'noty/src/api.js' {
  declare module.exports: $Exports<'noty/src/api'>;
}
declare module 'noty/src/button.js' {
  declare module.exports: $Exports<'noty/src/button'>;
}
declare module 'noty/src/index.js' {
  declare module.exports: $Exports<'noty/src/index'>;
}
declare module 'noty/src/push.js' {
  declare module.exports: $Exports<'noty/src/push'>;
}
declare module 'noty/src/utils.js' {
  declare module.exports: $Exports<'noty/src/utils'>;
}
