// flow-typed signature: a9df409b250dcbc8b6c239418a9a2be5
// flow-typed version: <<STUB>>/react-leaflet-ant-path_v^1.1.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-leaflet-ant-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-leaflet-ant-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-leaflet-ant-path/dist/react-leaflet-ant-path' {
  declare module.exports: any;
}

declare module 'react-leaflet-ant-path/tests/AntPath.spec' {
  declare module.exports: any;
}

declare module 'react-leaflet-ant-path/tests/enzyme' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-leaflet-ant-path/dist/react-leaflet-ant-path.js' {
  declare module.exports: $Exports<'react-leaflet-ant-path/dist/react-leaflet-ant-path'>;
}
declare module 'react-leaflet-ant-path/tests/AntPath.spec.jsx' {
  declare module.exports: $Exports<'react-leaflet-ant-path/tests/AntPath.spec'>;
}
declare module 'react-leaflet-ant-path/tests/enzyme.js' {
  declare module.exports: $Exports<'react-leaflet-ant-path/tests/enzyme'>;
}
